name: thug-memes # you probably want to 'snapcraft register <name>'
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Command line Thug Meme generator written in Python # 79 char long summary
description: |
  Command line Thug Meme generator written in Python

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  thug:
    command: thug
    plugs: [home, x11]
  
parts:
  thug-memes:
    plugin: python
    source: https://github.com/jerry-git/thug-memes
    source-type: git
    source-tag: '0.1.0'
    stage-packages:
      - libsm6
      - libxrender1
      - libxext6
  dlib:
    plugin: python
    stage-packages:
      - build-essential
      - cmake
      - libopenblas-dev
      - liblapack-dev 
      - libx11-dev
      - libgtk-3-dev
      - python-dev
      - python3-dev
    python-packages:
      - numpy
      - dlib

environment:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

